### ISSUE TITLE
Incorrect window sizes when creating.

### ISSUE THREAD

**Issue by AlexanderZhirov** [MoAlyousef/cfltk#214]
Noticed stretched windows when creating. For every 100 pixels, 10 extra pixels are added.

![изображение](https://user-images.githubusercontent.com/37277056/176653011-f7710e02-6387-4c2e-9f44-850decd7c606.png)

![изображение](https://user-images.githubusercontent.com/37277056/176653225-a145a2ab-41b9-4a3c-989c-64fe3978cba2.png)

**Comment by MoAlyousef** [comment]
Are you by chance using a scale factor for your screen/display that’s at 110%?

**Comment by AlexanderZhirov** [comment]
> Are you by chance using a scale factor for your screen/display that’s at 110%?

Yes, you're right. Strange. And why then does scaling not affect the C++ FLTK program? 🧐

**Comment by MoAlyousef** [comment]
Fltk 1.3.x was dpi-unaware. Cfltk uses fltk 1.4 which is dpi-aware.

**Comment by MoAlyousef** [comment]
Most welcome 🙏
