### ISSUE TITLE
Unable to compile on Windows with GCC.

### ISSUE THREAD

**Issue by Pokeman2003** [MoAlyousef/cfltk#216]
Perhaps I'm just being stupid, but any time I run cmake, it attempts to execute the MSVC compilation path and utilize nmake. That's the jist of what I'm getting, anyways, I have no experience with cmake. It has made compiling this an impossibility, which is a shame because I really do need to use this on a non-git project. Below is the error I get trying to compile it.

```
F:\Software Development\Sources\cfltk-main\src>cmake .. -D CMAKE_C_COMPILER="F:\Software Development\mingw32\bin\gcc.exe" -D CMAKE_CXX_COMPILER="F:\Software Development\mingw32\bin\g++.exe"
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified


-- Configuring incomplete, errors occurred!```

**Comment by Pokeman2003** [comment]
I may also be totally misunderstanding how to use this. I am pretty new to C programming, so that might be a problem.

**Comment by MoAlyousef** [comment]
CMake is a build-system generator. If it only finds nmake it will use it. On windows if it finds nothing it’ll still try to use nmake. You can try installing a different build syste like ninja and point CMake to it using `-DCMAKE_MAKE_PROGRAM="F:\ninja.exe"`

**Comment by Pokeman2003** [comment]
Would you mind breaking that down like I'm 3? I got that it's going to try to use NMake but I have no idea why that's the case, especially since I'm trying to set it up for MingW.
Does MSYS2 count as a build system compatible with CMake? My friend directed me towards it.

**Comment by MoAlyousef** [comment]
Yes msys2 is a saner way of using mingw on windows. It has a package manager which you can use to download the tools you need for the build:
```
pacman -S curl tar git $MINGW_PACKAGE_PREFIX-gcc $MINGW_PACKAGE_PREFIX-cmake $MINGW_PACKAGE_PREFIX-make $MINGW_PACKAGE_PREFIX-ninja --needed
source shell mingw64
git clone https://github.com/MoAlyousef/cfltk
cd cfltk
git submodule update --init --recursive
```
Then invoke cmake with your required flags like in the readme
