### ISSUE TITLE
[enhancement] Allow fully overriding widget draw routine

### ISSUE THREAD

**Issue by jkl1337** [MoAlyousef/cfltk#218]
Currently the Widget_Derived draw callback unconditionally calls the super draw function first before calling a custom callback. This makes it not possible to, say, derive a new button type which gets state and mouse handling but with fully custom drawing. It would be nice if the super draw function is wrapped and explicitly callable and it isn't called if a draw callback is set.

**Comment by MoAlyousef** [comment]
I've added WidgetBase::super_draw(flag) method which determines whether super::draw should be called or not. It's currently `#[doc(hidden)]` since I think wanting to fully override a widget's draw routine is kinda niche.
Example code:
```rust
use fltk::{prelude::*, *};

struct MyButton {
    btn: button::Button,
}

impl MyButton {
    pub fn new(s: &str) -> Self {
        let mut btn = button::Button::default_fill().with_label(s);
        btn.super_draw(false); // by default it's true
        btn.draw(|b| {
            fltk::draw::set_font(enums::Font::Courier, 18);
            fltk::draw::draw_box(enums::FrameType::DiamondUpBox, b.x(), b.y(), b.w(), b.h(), enums::Color::Cyan);
            fltk::draw::draw_text2(&b.label(), b.x(), b.y(), b.w(), b.h(), enums::Align::Center);
        });
        Self {
            btn
        }
    }
}

fn main() {
    let a = app::App::default().with_scheme(app::Scheme::Gtk);
    let mut win = window::Window::default().with_size(500, 300);
    let mut b = MyButton::new("Click");
    b.btn.set_callback(|_| println!("clicked"));
    win.end();
    win.show();
    a.run().unwrap();
}
```

**Comment by jkl1337** [comment]
Thanks that’ll work pretty nice!
