### ISSUE TITLE
not possible to interact with platform-specified API

### ISSUE THREAD

**Issue by poly000** [MoAlyousef/cfltk#220]
I am writing an OSD lyrics app for wayland with `fltk-rs`, which uses `fltk-sys` generated from cfltk
As cfltk does not expose fl_wl_surface, it's really a headache to correctly link same fltk lib

**Comment by MoAlyousef** [comment]
When you call window.raw_handle() on a window on wayland, it returns the wl_surface pointer. 
Similarly you can use the raw-window-handle crate with fltk-rs which can give you the wl_surface.
Is that not enough?
It's also not clear to me how this affects linking.

**Comment by poly000** [comment]
oh.. really sorry for that
I thought I need to link to `fl_wl_surface` and have no another way to get `wl_surface` pointer
Also, much thanks to your help

**Comment by poly000** [comment]
btw, I guess I should tell fltk-rs to mention wl_surface to their RawHandle comment, thus I could search wl_surface and locate RawHandle.

**Comment by poly000** [comment]
No... according to [FLTK 1.4 os issue](https://www.fltk.org/doc-1.4/osissues.html), you cannot get a `wl_surface *` with `fl_xid(wind)`
you should use `fl_wl_surface(fl_wl_xid(wind))`

**Comment by MoAlyousef** [comment]
This should be fixed here:
https://github.com/MoAlyousef/cfltk/blob/b04709c276dd6d83f618bf0e43b3fa08894fb838/src/cfl_window.cpp#L267

Can you try with:
```toml
[depenendencies]
fltk = { git = "https://github.com/fltk-rs/fltk-rs", features = ["use-wayland"] } 
```

**Comment by MoAlyousef** [comment]
Also can you provide a repro?
I think the previous implementation was correct.

**Comment by MoAlyousef** [comment]
It seems fl_xid returns an X11 id even on wayland, I’ll have to use conditional compilation there as well to use fl_wl_xid.

**Comment by MoAlyousef** [comment]
I've pushed a second fix, can you try it by adding fltk-rs as a git dependency and running cargo update?

**Comment by poly000** [comment]
> I've pushed a second fix, can you try it by adding fltk-rs as a git dependency and running cargo update?

oh. sorry I am doing army training (as a Chinese student), I forgot to push my code.
may you could test with evcxr_repl and use
wayland_client with feature `client_system` and obtain on ObjectId with from_ptr

**Comment by MoAlyousef** [comment]
I tried the lastest build with the following code:
```rust
use fltk::{prelude::*, *};
use wayland_client::Proxy;

fn main() {
    let a = app::App::default();
    let mut wind = window::Window::new(100, 100, 400, 300, "My Window");
    wind.end();
    wind.show();
    let ptr = wind.raw_handle() as _;
    let val = unsafe { wayland_client::backend::ObjectId::from_ptr(wayland_client::protocol::wl_surface::WlSurface::interface(), ptr).unwrap()} ;
    dbg!(val);
    a.run().unwrap();
}
```
And it prints:
```
[fltk/examples/temp.rs:11] val = ObjectId(wl_surface@11)
```

**Comment by poly000** [comment]
seems working properly
