### ISSUE TITLE
Cairo support is missed in cfltk

### ISSUE THREAD

**Issue by w568w** [MoAlyousef/cfltk#223]
Thanks for all the work done to make foreign language binding possible!

I see that most of the classes have been re-exported. However, [special Cairo support for FLTK](https://github.com/fltk/fltk/blob/master/src/Fl_Cairo.cxx) seems to be [missed out](https://github.com/search?q=repo%3AMoAlyousef%2Fcfltk+cairo&type=code). Since Cairo is [enabled by default in most cases](https://github.com/search?q=repo%3AMoAlyousef%2Fcfltk+OPTION_USE_CAIRO&type=code), is there any other reason for not exporting this part of the interface? 

Cairo has more advanced drawing functions than FLTK without using OpenGL. Therefore, it can do some work that FLTK cannot do, such as rendering translucent shapes. Otherwise, sometimes only [relatively low performance solutions](https://github.com/fltk-rs/fltk-rs/discussions/987) can be used.

*p.s.* Since the maintainers of this code repository are basically the same as [fltk-rs](https://github.com/fltk-rs/fltk-rs), I would also like to request here that this group of interfaces be integrated into fltk-rs in the future.

**Comment by MoAlyousef** [comment]
Thank you for your kind words.
The problem is that Cairo support in FLTK is an implementation detail on x11 and wayland. Adding the CairoExt FLTK feature will require support on Windows and MacOS as well.
It will also require exposing Cairo functionality since without it, not much can be done.
That said Cairo can be used without adding any additional code to cfltk or fltk-rs.
I followed the discussion on fltk-general.
This for example mimics the boxes example that was given:
```rust
use cairo::{Context, Format, ImageSurface};
use fltk::{enums::*, prelude::*, *};
use std::{cell::RefCell, rc::Rc};

#[derive(Clone)]
struct CairoWidget {
    frm: frame::Frame,
    opacity: Rc<RefCell<f64>>,
}

impl CairoWidget {
    pub fn new(x: i32, y: i32, w: i32, h: i32, label: &str) -> Self {
        let mut frm = frame::Frame::new(x, y, w, h, None).with_label(label);
        let surface = ImageSurface::create(Format::ARgb32, w, h).expect("Couldn’t create surface");
        let ctx = Context::new(&surface).unwrap();
        let opacity = Rc::from(RefCell::from(1.0));
        frm.draw({
            let opacity = opacity.clone();
            move |w| {
                // fill rectangle with the given color
                // BGRA to avoid rearranging things for FLTK to understand
                let (r, g, b) = w.color().to_rgb();
                ctx.set_source_rgba(
                    b as f64 / 255.,
                    g as f64 / 255.,
                    r as f64 / 255.,
                    *opacity.borrow(),
                );
                ctx.paint().unwrap();
                surface
                    .with_data(|s| {
                        let mut rgb =
                            image::RgbImage::new(s, w.w(), w.h(), ColorDepth::Rgba8).unwrap();
                        rgb.draw(w.x(), w.y(), w.w(), w.h());
                    })
                    .unwrap();
            }
        });
        Self { frm, opacity }
    }

    pub fn set_opacity(&mut self, val: f64) {
        *self.opacity.borrow_mut() = val;
    }

    pub fn opacity(&self) -> f64 {
        *self.opacity.borrow()
    }

    pub fn draw<F: FnMut(&mut Self) + 'static>(&mut self, mut cb: F) {
        let mut frm = self.clone();
        let mut old_cb = unsafe { frm.draw_data().unwrap() };
        self.frm.draw(move |_| {
            old_cb();
            cb(&mut frm);
        });
    }
}

fltk::widget_extends!(CairoWidget, frame::Frame, frm);

fn main() {
    let app = app::App::default().with_scheme(app::AppScheme::Gtk);
    let mut win = window::Window::new(100, 100, 300, 300, "Cairo");
    win.set_color(Color::White);

    let mut box1 = CairoWidget::new(0, 0, 100, 100, "Box1");
    box1.set_color(Color::from_rgb(0, 0, 255));
    box1.set_opacity(0.4);
    let mut box2 = CairoWidget::new(75, 75, 100, 100, "Box2");
    box2.set_color(Color::Red);
    box2.set_opacity(0.4);
    let mut box3 = CairoWidget::new(150, 150, 100, 100, "Box3");
    box3.set_color(Color::Green);
    box3.set_opacity(0.4);

    win.end();
    win.show();

    app.run().unwrap();
}
```
![image](https://github.com/MoAlyousef/cfltk/assets/37966791/228c6f84-c081-40f8-b88d-6be7ac1603fe)

**Comment by w568w** [comment]
> The problem is that Cairo support in FLTK is an implementation detail on x11 and wayland. Adding the CairoExt FLTK feature will require support on Windows and MacOS as well.

I saw https://github.com/fltk/fltk/blob/6fbc7ad86eadeb1b5405e322553bff4b7aeb0775/src/Fl_Cairo.cxx#L40-L41 claimed that "_Cairo is currently supported for ... Windows, macOS (Apple Quartz), X11, Wayland._" If I got it right, is it possible to add a compile flag to control the enabling of Cairo on these platforms (i.e. Windows and macOS)?

> It will also require exposing Cairo functionality since without it, not much can be done.

I suppose that if you import the identical version of Cairo and pass in the Cairo context exported by FLTK, the functions are interoperable. To verify this I wrote a simple demo with [pangocairo](https://crates.io/crates/pangocairo):

```rust
// ffi.rs
use std::os::raw::c_char;

unsafe extern "C" {
    fn fl_cairo_gc() -> *mut c_char; // exported in FL/x11.H
}
``` 

```rust
// main.rs
use pangocairo::cairo::{Context, ffi::cairo_t};
// ... other imports omitted ...

fn draw_box_with_alpha(rect: &Rect, color: Color, alpha: u8) {
    let ctx = unsafe { Context::from_raw_borrow(ffi::cairo_cur() as *mut cairo_t) };
    let (r, g, b) = color.to_rgb();
    ctx.save().unwrap();
    ctx.move_to(rect.x as f64, rect.y as f64);
    ctx.line_to((rect.x + rect.w) as f64, rect.y as f64);
    ctx.line_to((rect.x + rect.w) as f64, (rect.y + rect.h) as f64);
    ctx.line_to(rect.x as f64, (rect.y + rect.h) as f64);
    ctx.close_path();
    ctx.set_source_rgba(r as f64 / 255.0, g as f64 / 255.0, b as f64 / 255.0, alpha as f64 / 255.0);
    ctx.fill().unwrap();
    ctx.restore().unwrap();
}
```

And `draw_box_with_alpha()` works nice on X11 platform.

> I followed the discussion on fltk-general. 
> This for example mimics the boxes example that was given:

As you have mentioned [here](https://github.com/fltk-rs/fltk-rs/discussions/987#discussioncomment-1612730), `RGBImage` is a high-level method for drawing... But since the drawing process goes through a bitmap buffer, it also has much poorer performance than the low-level drawing primitives, provided by graphic drivers. 

In my case, it takes \~10 ms to draw 10 transparent rectangles with cached and shared `RGBImage`, while `draw_box_with_alpha()` only takes \~100 µs. That is almost 100x drawing time. If I want to draw more shapes (and animations), it is very difficult to maintain 60 FPS with `RGBImage`, isn't it?

**Comment by MoAlyousef** [comment]
I guess it's possible to expose the raw Cairo context from FLTK. This will require the user to use the cairo (or pangocairo) crates.
I'll try to implement it.

**Comment by MoAlyousef** [comment]
It should now be possible to get CairoExt support in fltk-rs.
It requires adding the `cairoext` feature flag.

It requires calling `app::cairo::set_autolink_context(true);` before any windows are shown.
Then to get the cairo context you can either use `app::cairo::cc() or app::cairo::make_current(&widget)`. It will return a void pointer which requires using the cairo-rs crate's Context::from_raw_* methods.
```rust
use cairo::{Context, Format, ImageSurface};
use fltk::{enums::*, prelude::*, draw::Rect, *};
use std::{cell::RefCell, rc::Rc};

fn draw_box_with_alpha(ctx: Context, rect: &Rect, color: Color, alpha: u8) {
    let (r, g, b) = color.to_rgb();
    ctx.save().unwrap();
    ctx.move_to(rect.x as f64, rect.y as f64);
    ctx.line_to((rect.x + rect.w) as f64, rect.y as f64);
    ctx.line_to((rect.x + rect.w) as f64, (rect.y + rect.h) as f64);
    ctx.line_to(rect.x as f64, (rect.y + rect.h) as f64);
    ctx.close_path();
    ctx.set_source_rgba(r as f64 / 255.0, g as f64 / 255.0, b as f64 / 255.0, alpha as f64 / 255.0);
    ctx.fill().unwrap();
    ctx.restore().unwrap();
}

#[derive(Clone)]
struct CairoWidget {
    frm: frame::Frame,
    alpha: Rc<RefCell<u8>>,
}

impl CairoWidget {
    pub fn new(x: i32, y: i32, w: i32, h: i32, label: &str) -> Self {
        let mut frm = frame::Frame::new(x, y, w, h, None).with_label(label);
        let alpha = Rc::from(RefCell::from(255));
        frm.draw({
            let alpha = alpha.clone();
            move |w| {
                let ctx = unsafe { Context::from_raw_none(app::cairo::cc() as _) };
                draw_box_with_alpha(ctx, &Rect {x : w.x(), y : w.y(), w : w.w(), h : w.h()}, w.color(), *alpha.borrow());
            }
        });
        Self { frm, alpha }
    }

    pub fn set_alpha(&mut self, val: u8) {
        *self.alpha.borrow_mut() = val;
    }

    pub fn alpha(&self) -> u8 {
        *self.alpha.borrow()
    }

    pub fn draw<F: FnMut(&mut Self) + 'static>(&mut self, mut cb: F) {
        let mut frm = self.clone();
        let mut old_cb = unsafe { frm.draw_data().unwrap() };
        self.frm.draw(move |_| {
            old_cb();
            cb(&mut frm);
        });
    }
}

fltk::widget_extends!(CairoWidget, frame::Frame, frm);

fn main() {
    let app = app::App::default().with_scheme(app::AppScheme::Gtk);
    app::cairo::set_autolink_context(true);
    let mut win = window::Window::new(100, 100, 300, 300, "Cairo");
    win.set_color(Color::White);

    let mut box1 = CairoWidget::new(0, 0, 100, 100, "Box1");
    box1.set_color(Color::from_rgb(0, 0, 255));
    box1.set_alpha(100);
    let mut box2 = CairoWidget::new(75, 75, 100, 100, "Box2");
    box2.set_color(Color::Red);
    box2.set_alpha(100);
    let mut box3 = CairoWidget::new(150, 150, 100, 100, "Box3");
    box3.set_color(Color::Green);
    box3.set_alpha(100);

    win.end();
    win.show();

    app.run().unwrap();
}
```

**Comment by w568w** [comment]
Thank a lot! :heart:

I have verified usability on Linux (X11 / Wayland). If I find problems on Windows/macOS, I will open a new issue later.
