### ISSUE TITLE
we need windows xp support

### ISSUE THREAD

**Issue by jiangyubao** [MoAlyousef/cfltk#226]
curl: (22) The requested URL returned error: 404
  thread 'main' panicked at 'Download bundled libraries from "https://github.com/MoAlyousef/cfltk/releases/latest/download/lib_i686-pc-windows-gnu.tar.gz" failed', /Users/jiangyb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fltk-sys-1.4.12/build/bundled.rs:30:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by MoAlyousef** [comment]
86-bit Windows XP should be supported if you build without the fltk-bundled flag. I can’t provide prebuilt binaries for an OS I don’t have access to in CI or locally. 
If you have such a system, you’ll need CMake and a C++ compiler when running the Rust build.

**Comment by jiangyubao** [comment]
you can use Windows 7 32-bit to build your project, and it can be run at windows xp
