### ISSUE TITLE
Where did you get the `Fl_load_font` function from?

### ISSUE THREAD

**Issue by KyrietS** [MoAlyousef/cfltk#238]
Hi, I need to load a custom font in FLTK and all my google searches direct me to this repo. Apparently your C bindings for FLTK have these 2 functions:

```
int Fl_load_font(const char *path);
void Fl_unload_font(const char *path);
```

I need them so much, but they are nowhere to be found in the official FLTK repo (master branch). So my question is, where did you get these functions from? Where are they implemented?

**Comment by MoAlyousef** [comment]
Hi

You can find the implementation here:
https://github.com/MoAlyousef/cfltk/blob/main/src/cfl_font.cpp

I got this from the fltk-general forum (with minor modifications):
https://groups.google.com/g/fltkgeneral/c/ynEhgU8qr4U/m/t9YZ2sjGAQAJ

**Comment by KyrietS** [comment]
Oh, so it's your own addition to FLTK API. Got it 😄👍
Thank you for your answer!
